### ISSUE TITLE
docs: clarify relation to openshift

### ISSUE THREAD

**Issue by ibotty** [projectatomic/commissaire#120]
I cannot tell from the documentation whether commissaire is supposed to work with openshift. It would be great if it could.

**Comment by ashcrow** [comment]
Good note! It is supposed to be able to work with OpenShift and/or Kubernetes. I'll see what I can to clarify that in the documentation. Thank you for pointing it out!

**Comment by ashcrow** [comment]
@ibotty let me know if you think we need more changes to clarify that commissaire works with OpenShift.

Again, thank you for your feedback!

**Comment by ibotty** [comment]
Yes. I addresses all points I asked for. It would be great to know whether other network overlays like openshift-sdn (or weave, or whatever else exists) work with commissaire. At least openshift-sdn is pretty tightly integrated with openshift, so it might make sense to support it in commissaire, because setting up openshift-sdn by itself is pretty much the same as adding the node anyway.

**Comment by ashcrow** [comment]
At the moment we are working with ```Flannel```. However, I fully expect us to implement ```openshift-sdn``` integration since it is commonly used as well.
