### ISSUE TITLE
walkthrough.rst: broken `make-mime.py` link

### ISSUE THREAD

**Issue by timlnx** [projectatomic/commissaire#128]
Under [Automatic Registration](http://commissaire.readthedocs.io/en/latest/walkthrough.html#automatic-registration) there is a link to `make-mime.py` but that link is broken. D'oh!

> Before we start you will need [make-mime.py](http://bazaar.launchpad.net/~cloud-init-dev/cloud-init/trunk/view/head:/tools/make-mime.py) script from cloud-init’s tools directory.

```
$ curl http://bazaar.launchpad.net/~cloud-init-dev/cloud-init/trunk/view/head:/tools/make-mime.py
<html>
  <head><title>Not Found</title></head>
  <body>
    <h1>Not Found</h1>
    <p>The resource could not be found.
<br/>
<!--  --></p>
    <hr noshade>
    <div align="right">WSGI Server</div>
  </body>
</html>
```

I'm not sure what the correct location of this script is. I tried trimming items off of the URL but they all weren't found.

**Comment by timlnx** [comment]
Found another occurrence

> Then, use make-mime.py to put it all together into a user-data file we can use in cloud providers.

**Comment by ashcrow** [comment]
I found https://git.launchpad.net/cloud-init/tree/tools/make-mime.py

@mbarnes Why don't we pull it in (assuming the license is friendly)? In the next release I'd like to make this part of ``commctl``.

**Comment by mbarnes** [comment]
@ashcrow Agreed, although we'll have to remember to refresh it periodically to pick up any upstream changes.

**Comment by ashcrow** [comment]
@mbarnes I literally plan on replacing it with commctl in the next release or the one after that. Until then, let's snag it.

**Comment by ashcrow** [comment]
@mbarnes actually, I'm going to steal this and just do it now 😆

**Comment by ashcrow** [comment]
Work done in https://github.com/projectatomic/commctl/pull/33

**Comment by mbarnes** [comment]
The work got merged, so closing this.
