### ISSUE TITLE
Models should know default values

### ISSUE THREAD

**Issue by mbarnes** [projectatomic/commissaire#147]
I had some old host records in my test environment that predated the recently added `remote_user` field which defaults to `"root"`.  Because this field was missing it broke various REST endpoints because the server couldn't assemble a `Host` model from the old records.

It's likely we'll be adding more new fields to the models over time, so to future-proof the models better I think they should know about default values so they can gracefully handle missing fields when parsing JSON data.

**Comment by ashcrow** [comment]
@mbarnes if you have not done so already, please make a card for this work. I completely agree it is worth pursuing.

**Comment by mbarnes** [comment]
https://trello.com/c/9pQYl1Pq/

**Comment by ashcrow** [comment]
Thanks @mbarnes!

**Comment by ashcrow** [comment]
@mbarnes doe ls the latest changes to models adding default values resolves this issue?

**Comment by mbarnes** [comment]
I'd like a test case specifically for my original problem scenario: mock load a minimal ("old") host/cluster record and verify all defaults.  I notice https://github.com/projectatomic/commissaire/commit/236914afbdc011ee7c25c0d3e542072cb6d13a84 didn't add any tests, and I don't know if any of the existing tests cover this.

Do you know offhand if we have this already?  If not I can cook something up.

**Comment by ashcrow** [comment]
I should have added tests but for some reason I didn't :sleepy:. PR created.
