### ISSUE TITLE
"atomic" is more of model, not a distribution

### ISSUE THREAD

**Issue by cgwalters** [projectatomic/commissaire#194]
Right now we have e.g. https://github.com/projectatomic/commissaire/blob/b43ca2b9b33ab91def3f0c08a47f2d6fb66fb31a/src/commissaire/oscmd/atomic.py at the same level as `fedora.py`, which is wrong, because there are Atomic Host variants of Fedora/CentOS/RHEL.

Also, the `and does not allow installing packages` part is no longer true :smile:

**Comment by cgwalters** [comment]
Also, we should follow the upstream thread in https://lists.projectatomic.io/projectatomic-archives/atomic-devel/2016-August/msg00054.html and update these.

**Comment by cgwalters** [comment]
Also, comments like this are then also wrong:

```
        # Special case for atomic: Since Atomic doesn't advertise itself
        # and instead calls itself 'redhat' or 'centos' or 'fedora', we
        # need to check for 'atomicos' in other ansible_cmdline facts.
        atomic_os_types = {
            'redhat': '/ostree/rhel-atomic-host',
            'centos': '/ostree/centos-atomic-host',
            'fedora': '/ostree/fedora-atomic'
        }
```

**Comment by ashcrow** [comment]
@cgwalters good points.

What is your recommendation for properly sensing if an OS is using the Atomic model today?

**Comment by cgwalters** [comment]
Some projects [use the existence of `/run/ostree-booted`](https://github.com/openshift/openshift-ansible/blob/d365ed2df542efa9cfa96fb468761cf2242ce8e5/roles/openshift_facts/tasks/main.yml#L2) which says whether or not the system uses ostree, however we don't quite have an equivalent model for `rpm-ostree` yet, though one could take the combination of the former and the existence of the latter in `$PATH`.  We'll improve this.

**Comment by mbarnes** [comment]
I thought the plan was to indicate atomic in `/etc/os-release` by way of the `VARIANT` field.
https://bugzilla.redhat.com/show_bug.cgi?id=1200122#c36

Has that not yet propagated?  Seems much more straight-forward.

**Comment by ashcrow** [comment]
I think jlebon was looking into that @mbarnes.

@jlebon do you know if that is still on going?

**Comment by jlebon** [comment]
They're two separate issues. The RHBZ above was for setting the `VARIANT_ID` to `atomic.host`. Though it seems like this hasn't taken effect yet (as can be seen from the last comment there and also https://pagure.io/fedora-atomic/issue/6).

What I worked on was a feature that adds the tree version number (e.g. `7.2.6`) to the `VERSION` and `PRETTY_NAME` fields.

**Comment by ashcrow** [comment]
@jlebon thanks for the clarification!

**Comment by ashcrow** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;vmsbQPrs&#x2F;411-2-multi-host-mgr-clarify-atomic-as-a-model"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> (2) [multi-host-mgr] Clarify Atomic as a model</a>
