### ISSUE TITLE
document some user stories

### ISSUE THREAD

**Issue by goern** [projectatomic/commissaire#64]
Could you write down, or point to, some user stories that show us what to do with commissaire? Thx!

**Comment by ashcrow** [comment]
@goern are you looking more for use cases or how to stand up the service?

**Comment by goern** [comment]
the first :)

**Comment by ashcrow** [comment]
@goern sure, we can do that :smile: I'll add it to our backlog.

https://trello.com/c/neE0AFve/171-multi-host-mgr-update-documentation-with-use-cases

**Comment by ashcrow** [comment]
I've added some update information with a few basic use cases. It should become a bigger list as time goes on. @goern does that work?

**Comment by goern** [comment]
Cool, thx. So it is explicitly not used for kickstarting aka initial
provisioning the hosts?

-- 
Principal Software Engineer - Systems Design & Engineering
Mobile: +49 171 2801345

Red Hat GmbH, http://www.de.redhat.com/, Sitz: Grasbrunn,
Handelsregister: Amtsgericht München, HRB 153243,
Geschäftsführer: Paul Argiry, Charles Cachera, Michael Cunningham, Michael
O'Neill

**Comment by ashcrow** [comment]
@goern correct. It expects something such as CloudForms, Katello, Satellite, or a cloud specific console to handle traditional host provisioning. Upon first boot is when commissaire takes care of registration with a container manager and operational commands.

Does that answer the questions?
